In [2]:
import pandas as pd
df=pd.read_csv("data1.csv")
df.shape

(284807, 31)

In [1]:
import os

size = os.path.getsize("data1.csv")

print(size)
print(size/1024)
print(size/1024/1024)

150828752
147293.703125
143.8415069580078

In [4]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.175161e-15,3.384974e-16,-1.379537e-15,2.094852e-15,1.021879e-15,1.494498e-15,-5.620335e-16,1.149614e-16,-2.414189e-15,...,1.628620e-16,-3.576577e-16,2.618565e-16,4.473914e-15,5.109395e-16,1.686100e-15,-3.661401e-16,-1.227452e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [2]:
#class distribution

df['Class'].value_counts()
df['Class'].value_counts(normalize=True)

Class
0    0.998273
1    0.001727
Name: proportion, dtype: float64

In [ ]:
fraud_sample = df[df['Class']==1].iloc[0]
#fraud_sample
fraud_input = fraud_sample.drop('Class')
print(fraud_input)

In [5]:
fraud_row = df[df['Class']==0].iloc[50]

test_input = fraud_row.drop('Class')

print(test_input)


#print(fraud_row)

Time      35.000000
V1         1.199356
V2         0.129953
V3         0.863585
V4         1.002635
V5        -0.783761
V6        -0.884679
V7        -0.040743
V8        -0.208069
V9         0.392478
V10       -0.248178
V11       -0.095363
V12        1.314131
V13        1.091681
V14       -0.409346
V15       -0.577994
V16       -0.581284
V17        0.212343
V18       -0.893181
V19       -0.020653
V20       -0.072620
V21       -0.042468
V22        0.198474
V23       -0.033010
V24        1.013290
V25        0.559098
V26        0.401818
V27       -0.005865
V28        0.017936
Amount     0.990000
Name: 50, dtype: float64

In [2]:
from sklearn.model_selection import train_test_split
X=df.drop('Class',axis=1)
y=df['Class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)
print(X_train.shape)
print(X_test.shape)
print("\n=== TEST SET ===")
print(y_test.value_counts())
print(y_test.value_counts(normalize=True) * 100)
print("=== TRAIN SET ===")
print(y_train.value_counts())
print(y_train.value_counts(normalize=True) * 100)

(227845, 30)
(56962, 30)

=== TEST SET ===
Class
0    56864
1       98
Name: count, dtype: int64
Class
0    99.827955
1     0.172045
Name: proportion, dtype: float64
=== TRAIN SET ===
Class
0    227451
1       394
Name: count, dtype: int64
Class
0    99.827075
1     0.172925
Name: proportion, dtype: float64

In [3]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

pass_through_features = ['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
                   'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
                   'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28']
features_to_scale = ['Time', 'Amount']

preprocessor = ColumnTransformer(
    transformers=[
        ('features_to_scale ', 'passthrough', features_to_scale),
        ('pass_through_features', 'passthrough', pass_through_features)

    ]
)

from sklearn.linear_model import LogisticRegression

pipeline = Pipeline(
    [
        ('preprocessor', preprocessor),
        ('model', LogisticRegression(
            #class_weight='balanced',
            random_state=42,
            max_iter=100  
         )
        ) 
    ]
)
pipeline.fit(X_train, y_train)
Y_pred = pipeline.predict(X_test)
y_probs = pipeline.predict_proba(X_test)[:, 1]
threshold = 0.9

y_pred_custom = (y_probs >= threshold).astype(int)
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,y_pred_custom))
print(confusion_matrix(y_test,y_pred_custom))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.78      0.67      0.72        98

    accuracy                           1.00     56962
   macro avg       0.89      0.84      0.86     56962
weighted avg       1.00      1.00      1.00     56962

[[56845    19]
 [   32    66]]

C:\Users\SURYANSH\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [6]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)
y_train_smote.value_counts()

pipeline.fit(X_train_smote, y_train_smote)
y_pred_smote = pipeline.predict(X_test)
print(classification_report(y_test,y_pred_smote))
print(confusion_matrix(y_test,y_pred_smote))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99     56864
           1       0.07      0.91      0.12        98

    accuracy                           0.98     56962
   macro avg       0.53      0.94      0.56     56962
weighted avg       1.00      0.98      0.99     56962

[[55591  1273]
 [    9    89]]

C:\Users\SURYANSH\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [4]:
from sklearn.ensemble import RandomForestClassifier
pipeline_rf = Pipeline(
    [
        ('preprocessor', preprocessor),
        ('rf_model', RandomForestClassifier(
                    random_state=42,
                    n_estimators=20,
                    n_jobs=-1
         )
        )
    ]
)
pipeline_rf.fit(X_train, y_train)
y_pred_rf = pipeline_rf.predict(X_test)
y_probs_rf = pipeline_rf.predict_proba(X_test)[:, 1]
threshold_rf = 0.4
y_pred_rf_custom = (y_probs_rf >= threshold_rf).astype(int)
print(classification_report(y_test,y_pred_rf_custom))
print(confusion_matrix(y_test,y_pred_rf_custom))   

# from sklearn.model_selection import StratifiedKFold
# from sklearn.model_selection import cross_val_score
# cv = StratifiedKFold(
#     n_splits=5,
#     shuffle=True,
#     random_state=42
# )
# scores = cross_val_score(
#     pipeline_rf,
#     X_train,
#     y_train,
#     cv=cv,
#     scoring='recall'
# )

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.90      0.87      0.89        98

    accuracy                           1.00     56962
   macro avg       0.95      0.93      0.94     56962
weighted avg       1.00      1.00      1.00     56962

[[56855     9]
 [   13    85]]

In [10]:
# print(
#     pipeline_rf.predict_proba(
#         X_test.iloc[:10]
#     )[:,1]
# )

fraud_probs = pipeline_rf.predict_proba(
    X_test[y_test == 1]
)[:,1]

print(sorted(fraud_probs)[:20])

[np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.1), np.float64(0.1), np.float64(0.15), np.float64(0.25), np.float64(0.45), np.float64(0.45), np.float64(0.45), np.float64(0.5), np.float64(0.5), np.float64(0.55), np.float64(0.55)]

In [8]:

print(scores.mean())
print(scores.std())

NameError: name 'scores' is not defined

In [31]:
from xgboost import XGBClassifier
pipeline_xgb = Pipeline(
    [
        ('preprocessor', preprocessor),
        ('xgb_model', XGBClassifier(
            random_state=42,
            n_estimators=20  
         )
        )
    ]
)
pipeline_xgb.fit(X_train, y_train)
y_pred_xgb = pipeline_xgb.predict(X_test)
y_prob_xg = pipeline_xgb.predict_proba(X_test)[:, 1]
threshold_xgb = 0.8 
y_pred_xgb_custom = (y_prob_xg >= threshold_xgb).astype(int)
print(classification_report(y_test,y_pred_xgb_custom))
print(confusion_matrix(y_test,y_pred_xgb_custom))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.89      0.79      0.83        98

    accuracy                           1.00     56962
   macro avg       0.94      0.89      0.92     56962
weighted avg       1.00      1.00      1.00     56962

[[56854    10]
 [   21    77]]

In [44]:
from lightgbm import LGBMClassifier
pipeline_lgbm = Pipeline(
    [
        ('preprocessor', preprocessor),
        ('lgbm_model', LGBMClassifier(
            random_state=42,
            n_estimators=20  
         )
        )
    ]
)
pipeline_lgbm.fit(X_train, y_train)
y_pred_lgbm = pipeline_lgbm.predict(X_test)
y_prob_lgbm = pipeline_lgbm.predict_proba(X_test)[:, 1]
threshold_lgbm = 0.9
y_pred_lgbm_custom = (y_prob_lgbm >= threshold_lgbm).astype(int)
print(classification_report(y_test,y_pred_lgbm_custom))
print(confusion_matrix(y_test,y_pred_lgbm_custom))

[LightGBM] [Info] Number of positive: 394, number of negative: 227451
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013781 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7650
[LightGBM] [Info] Number of data points in the train set: 227845, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.001729 -> initscore=-6.358339
[LightGBM] [Info] Start training from score -6.358339
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.54      0.78      0.63        98

    accuracy                           1.00     56962
   macro avg       0.77      0.89      0.82     56962
weighted avg       1.00      1.00      1.00     56962

[[56798    66]
 [   22    76]]

C:\Users\SURYANSH\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
C:\Users\SURYANSH\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [2]:
import os

print(os.path.getsize("random_forest_pipeline.pkl")/1024/1024)

0.5062274932861328

In [3]:
legit_test = df[df["Class"] == 0].head(10)
legit_test.drop("Class", axis=1)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,0.084968,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.219633,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,-0.156742,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,...,0.052736,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,0.203711,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68

In [15]:
fraud_test = df[df["Class"] == 1].head(10)
fraud_test.drop("Class", axis=1)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
541,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.126911,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00
623,472.0,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,2.102339,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00
4920,4462.0,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.430022,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93
6108,6986.0,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,-0.171608,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00
6329,7519.0,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,0.009061,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00
6331,7526.0,0.008430,4.137837,-6.240697,6.675732,0.768307,-3.353060,-1.631735,0.154612,-2.795892,...,0.488378,0.364514,-0.608057,-0.539528,0.128940,1.488481,0.507963,0.735822,0.513574,1.00
6334,7535.0,0.026779,4.132464,-6.560600,6.348557,1.329666,-2.513479,-1.689102,0.303253,-3.139409,...,0.587743,0.370509,-0.576752,-0.669605,-0.759908,1.605056,0.540675,0.737040,0.496699,1.00
6336,7543.0,0.329594,3.712889,-5.775935,6.078266,1.667359,-2.420168,-0.812891,0.133080,-2.214311,...,0.269773,0.156617,-0.652450,-0.551572,-0.716522,1.415717,0.555265,0.530507,0.404474,1.00
6338,7551.0,0.316459,3.809076,-5.615159,6.047445,1.554026,-2.651353,-0.746579,0.055586,-2.678679,...,0.388307,0.208828,-0.511747,-0.583813,-0.219845,1.474753,0.491192,0.518868,0.402528,1.00
6427,7610.0,0.725646,2.300894,-5.329976,4.007683,-1.730411,-1.732193,-3.968593,1.063728,-0.486097,...,0.504646,0.589669,0.109541,0.601045,-0.364700,-1.843078,0.351909,0.594550,0.099372,1.00

In [12]:
legit_test = df[df["Class"] == 0].head(10)
fraud_test = df[df["Class"] == 1].head(10)
mixed_test = pd.concat([legit_test, fraud_test], axis=0)
mixed_test = mixed_test.drop("Class", axis=1)
print(mixed_test)

        Time        V1        V2        V3        V4        V5        V6  \
0        0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388
1        0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361
2        1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499
3        1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203
4        2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921
5        2.0 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728
6        4.0  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708
7        7.0 -0.644269  1.417964  1.074380 -0.492199  0.948934  0.428118
8        7.0 -0.894286  0.286157 -0.113192 -0.271526  2.669599  3.721818
9        9.0 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761
541    406.0 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545
623    472.0 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823
4920  4462.0 -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788
6108  6986.0 -4.397974  1.358367 -2.592844  2.679787 -1.128131 -1.706536
6329  7519.0  1.234235  3.019740 -4.304597  4.732795  3.624201 -1.357746
6331  7526.0  0.008430  4.137837 -6.240697  6.675732  0.768307 -3.353060
6334  7535.0  0.026779  4.132464 -6.560600  6.348557  1.329666 -2.513479
6336  7543.0  0.329594  3.712889 -5.775935  6.078266  1.667359 -2.420168
6338  7551.0  0.316459  3.809076 -5.615159  6.047445  1.554026 -2.651353
6427  7610.0  0.725646  2.300894 -5.329976  4.007683 -1.730411 -1.732193

            V7        V8        V9  ...       V20       V21       V22  \
0     0.239599  0.098698  0.363787  ...  0.251412 -0.018307  0.277838
1    -0.078803  0.085102 -0.255425  ... -0.069083 -0.225775 -0.638672
2     0.791461  0.247676 -1.514654  ...  0.524980  0.247998  0.771679
3     0.237609  0.377436 -1.387024  ... -0.208038 -0.108300  0.005274
4     0.592941 -0.270533  0.817739  ...  0.408542 -0.009431  0.798278
5     0.476201  0.260314 -0.568671  ...  0.084968 -0.208254 -0.559825
6    -0.005159  0.081213  0.464960  ... -0.219633 -0.167716 -0.270710
7     1.120631 -3.807864  0.615375  ... -0.156742  1.943465 -1.015455
8     0.370145  0.851084 -0.392048  ...  0.052736 -0.073425 -0.268092
9     0.651583  0.069539 -0.736727  ...  0.203711 -0.246914 -0.633753
541  -2.537387  1.391657 -2.770089  ...  0.126911  0.517232 -0.035049
623   0.325574 -0.067794 -0.270953  ...  2.102339  0.661696  0.435477
4920  0.562320 -0.399147 -0.238253  ... -0.430022 -0.294166 -0.932391
6108 -3.496197 -0.248778 -0.247768  ... -0.171608  0.573574  0.176968
6329  1.713445 -0.496358 -1.282858  ...  0.009061 -0.379068 -0.704181
6331 -1.631735  0.154612 -2.795892  ...  0.488378  0.364514 -0.608057
6334 -1.689102  0.303253 -3.139409  ...  0.587743  0.370509 -0.576752
6336 -0.812891  0.133080 -2.214311  ...  0.269773  0.156617 -0.652450
6338 -0.746579  0.055586 -2.678679  ...  0.388307  0.208828 -0.511747
6427 -3.968593  1.063728 -0.486097  ...  0.504646  0.589669  0.109541

           V23       V24       V25       V26       V27       V28  Amount
0    -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62
1     0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69
2     0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66
3    -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50
4    -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99
5    -0.026398 -0.371427 -0.232794  0.105915  0.253844  0.081080    3.67
6    -0.154104 -0.780055  0.750137 -0.257237  0.034507  0.005168    4.99
7     0.057504 -0.649709 -0.415267 -0.051634 -1.206921 -1.085339   40.80
8    -0.204233  1.011592  0.373205 -0.384157  0.011747  0.142404   93.20
9    -0.120794 -0.385050 -0.069733  0.094199  0.246219  0.083076    3.68
541  -0.465211  0.320198  0.044519  0.177840  0.261145 -0.143276    0.00
623   1.375966 -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00
4920  0.172726 -0.087330 -0.156114 -0.542628  0.039566 -0.153029  239.93
6108 -0.436207 -0.053502  0.252405 -0.657488 -0.827136  0.849573   59.00
6329 -0.656805 -1.632653  1.488901  0.566797 -0.010016  0.146793    1.00
6331 -0.539528  0.128940  1.488481  0.507963  0.735822  0.513574    1.00
6334 -0.669605 -0.759908  1.605056  0.540675  0.737040  0.496699    1.00
6336 -0.551572 -0.716522  1.415717  0.555265  0.530507  0.404474    1.00
6338 -0.583813 -0.219845  1.474753  0.491192  0.518868  0.402528    1.00
6427  0.601045 -0.364700 -1.843078  0.351909  0.594550  0.099372    1.00

[20 rows x 30 columns]